PREFIX anki: <https://veyndan.com/foo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    anki:text a anki:field;
        rdfs:label "Text";
        anki:required true;
        rdf:value ?text.

    anki:uppercaseText a anki:field;
        rdfs:label "Uppercase Text";
        anki:required false;
        rdf:value ?uppercaseText.
}
WHERE {
    SELECT ?text (UCASE(?text) as ?uppercaseText) WHERE {
        ?textField a anki:field;
            rdfs:label "Text";
            rdf:value ?text.
    }
}
