PREFIX anki: <https://veyndan.com/foo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    anki:text a anki:field;
        rdfs:label "Text";
        anki:required true;
        rdf:value ?text.

    anki:uppercaseText a anki:field;
        rdfs:label "Uppercase Text";
        anki:required false;
        rdf:value ?uppercaseText.

    anki:simpleTemplate a anki:template;
        rdfs:label "Simple";
        anki:qfmt "{{Text}}";
        anki:afmt "{{FrontSide}}\n\n<hr id=answer>\n\n{{Uppercase Text}}".
}
FROM <file:myankiplugin/fields.ttl>
WHERE {
    SELECT ?text (UCASE(?text) AS ?uppercaseText) WHERE {
        OPTIONAL {
            ?textField a anki:field;
                rdfs:label "Text";
                rdf:value ?text.
        }
    }
}
