PREFIX anki: <https://veyndan.com/foo/>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT * WHERE {
    {
        SELECT ?person ?predicate ?object WHERE {
            BIND(wd:Q42 AS ?person)

            SERVICE <https://query.wikidata.org/sparql> {
                ?person ?predicate ?object.
            }
        }
    }

    # TODO Deleting this empty service below makes the service in the subquery get passed the ?person VALUE.
    #  File this bug.
    SERVICE <https://query.wikidata.org/sparql> {}
}
